name: Danger
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  danger:
    uses: numbata/danger-pr-comment/.github/workflows/danger-run.yml@v0.1.0
    with:
      ruby-version: '3.4'
      bundler-cache: true
    secrets: inherit
